In [2]:
import pandas as pd

In [5]:
df = pd.read_csv ('Employee.csv')
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

In [8]:
cols = ['LeaveOrNot']
df = df.drop(cols, axis=1)

In [11]:
df.isnull().any()

Education                    False
JoiningYear                  False
City                         False
PaymentTier                  False
Age                          False
Gender                       False
EverBenched                  False
ExperienceInCurrentDomain    False
dtype: bool

In [13]:
data.isnull().any()

Education                    False
JoiningYear                  False
City                         False
PaymentTier                  False
Age                          False
Gender                       False
EverBenched                  False
ExperienceInCurrentDomain    False
dtype: bool

In [14]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder

In [15]:
le = preprocessing.LabelEncoder()

In [18]:
data['Gender']=le.fit_transform(data['Gender'])
data

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
0,Bachelors,2017,Bangalore,3,34,1,No,0
1,Bachelors,2013,Pune,1,28,0,No,3
2,Bachelors,2014,New Delhi,3,38,0,No,2
3,Masters,2016,Bangalore,3,27,1,No,5
4,Masters,2017,Pune,3,24,1,Yes,2
...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,0,No,4
4649,Masters,2013,Pune,2,37,1,No,2
4650,Masters,2018,New Delhi,3,27,1,No,5
4651,Bachelors,2012,Bangalore,3,30,1,Yes,2
4652,Bachelors,2015,Bangalore,3,33,1,Yes,4

In [21]:
y=['Education','JoiningYear','City','PaymentTier','EverBenched']
for i in y:
    data[i]=le.fit_transform(data[i])
data

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
0,0,5,0,2,34,1,0,0
1,0,1,2,0,28,0,0,3
2,0,2,1,2,38,0,0,2
3,1,4,0,2,27,1,0,5
4,1,5,2,2,24,1,1,2
...,...,...,...,...,...,...,...,...
4648,0,1,0,2,26,0,0,4
4649,1,1,2,1,37,1,0,2
4650,1,6,1,2,27,1,0,5
4651,0,0,0,2,30,1,1,2
4652,0,3,0,2,33,1,1,4

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
w=scaler.fit_transform(data)
w

array([[-0.50773115,  1.03963837, -0.94273968, ...,  0.82155097,
        -0.33836521, -1.86490139],
       [-0.50773115, -1.10723275,  1.43287241, ..., -1.21720992,
        -0.33836521,  0.06055412],
       [-0.50773115, -0.57051497,  0.24506637, ..., -1.21720992,
        -0.33836521, -0.58126438],
       ...,
       [ 1.41141834,  1.57635615,  0.24506637, ...,  0.82155097,
        -0.33836521,  1.34419112],
       [-0.50773115, -1.64395053, -0.94273968, ...,  0.82155097,
         2.95538654, -0.58126438],
       [-0.50773115, -0.03379719, -0.94273968, ...,  0.82155097,
         2.95538654,  0.70237262]])